name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
          project_id: quizzo-425513
          credentials_json: ${{ secrets.GCP_API_KEY }}
      env:
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}

    - name: Run script
      run: streamlit run app.py
